version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    hostname: database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  nocodb:
    image: nocodb/nocodb
    ports:
      - "8080:8080"
    # volumes:
    #   - nocodb-data:/usr/app/data/
    environment:
      - NC_DB=pg://${DB_HOST}:${DB_PORT}?u=${DB_USER}&p=${DB_PASSWORD}&d=${DB_NAME}
      - NC_AUTH_JWT_SECRET=569a1821-0a93-45e8-87ab-eb857f20a010
    restart: always
    depends_on:
      - db
  sports-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db-data:
  nocodb-data:
